chain_id: 1
node_rpc: "https://rpc.flashbots.net/fast"
gas_price_endpoint: "https://gas-api.metaswap.codefi.network/networks/1"
keystore_dir: "keystore"
router_address: "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"
input_token: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" # ETH
output_token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" # USDC
fee_tier: 500 # 0.05%
gas_tip_multiplier: 1.0
#start_time: "2024-08-01T00:00:00Z"
#gas_limit: 300000
#min_return_amount: 7000000000 # 7000 USDC
weth: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
accounts:
  - address: "0x0000000000000000000001111111111111111111"
    passphrase: "123456"
    amount: 4000000000000000000 # 4 ETH
    #priv_key: "" # optional
    #recipient: "" # recipient wallet, default is account address.
    max_gas_fee: 200000000000000000 # 0.2 ETH, default is estimated from metamask API.
    #min_return_amount: 12000000000 # 12000 USDC, if omitted, use global value set above.
